const Countries = [
    { name: "India", dialCode: "+91", alpha2: "IN", code: "in" },
    { name: "Russia", dialCode: "+7", alpha2: "RU", code: "ru" },
    { name: "Kazakhstan", dialCode: "+7", alpha2: "KZ", code: "kz" },
    { name: "Japan", dialCode: "+81", alpha2: "JP", code: "jp" },
    { name: "South Korea", dialCode: "+82", alpha2: "KR", code: "kr" },
    { name: "Vietnam", dialCode: "+84", alpha2: "VN", code: "vn" },
    { name: "North Korea", dialCode: "+850", alpha2: "KP", code: "kp" },
    { name: "Hong Kong", dialCode: "+852", alpha2: "HK", code: "hk" },
    { name: "Macau", dialCode: "+853", alpha2: "MO", code: "mo" },
    { name: "Cambodia", dialCode: "+855", alpha2: "KH", code: "kh" },
    { name: "Laos", dialCode: "+856", alpha2: "LA", code: "la" },
    { name: "China", dialCode: "+86", alpha2: "CN", code: "cn" },
    { name: "Bangladesh", dialCode: "+880", alpha2: "BD", code: "bd" },
    { name: "Taiwan", dialCode: "+886", alpha2: "TW", code: "tw" },
    { name: "Turkey", dialCode: "+90", alpha2: "TR", code: "tr" },
    { name: "Pakistan", dialCode: "+92", alpha2: "PK", code: "pk" },
    { name: "Afghanistan", dialCode: "+93", alpha2: "AF", code: "af" },
    { name: "Sri Lanka", dialCode: "+94", alpha2: "LK", code: "lk" },
    { name: "Myanmar", dialCode: "+95", alpha2: "MM", code: "mm" },
    { name: "Maldives", dialCode: "+960", alpha2: "MV", code: "mv" },
    { name: "Canada", dialCode: "+1", alpha2: "CA", code: "ca" },
    { name: "United States", dialCode: "+1", alpha2: "US", code: "us" },
    { name: "Bahamas", dialCode: "+1242", alpha2: "BS", code: "bs" },
    { name: "Barbados", dialCode: "+1246", alpha2: "BB", code: "bb" },
    { name: "Anguilla", dialCode: "+1264", alpha2: "AI", code: "ai" },
    { name: "Antigua and Barbuda", dialCode: "+1268", alpha2: "AG", code: "ag" },
    { name: "Virgin Islands, British", dialCode: "+1284", alpha2: "VG", code: "vg" },
    { name: "Virgin Islands, U.S.", dialCode: "+1340", alpha2: "VI", code: "vi" },
    { name: "Bermuda", dialCode: "+1441", alpha2: "BM", code: "bm" },
    { name: "Grenada", dialCode: "+1473", alpha2: "GD", code: "gd" },
    { name: "Turks and Caicos Islands", dialCode: "+1649", alpha2: "TC", code: "tc" },
    { name: "Montserrat", dialCode: "+1664", alpha2: "MS", code: "ms" },
    { name: "Northern Mariana Islands", dialCode: "+1670", alpha2: "MP", code: "mp" },
    { name: "Guam", dialCode: "+1671", alpha2: "GU", code: "gu" },
    { name: "American Samoa", dialCode: "+1684", alpha2: "AS", code: "as" },
    { name: "Saint Lucia", dialCode: "+1758", alpha2: "LC", code: "lc" },
    { name: "Dominica", dialCode: "+1767", alpha2: "DM", code: "dm" },
    { name: "Saint Vincent and the Grenadines", dialCode: "+1784", alpha2: "VC", code: "vc" },
    { name: "Dominican Republic", dialCode: "+1849", alpha2: "DO", code: "do" },
    { name: "Trinidad and Tobago", dialCode: "+1868", alpha2: "TT", code: "tt" },
    { name: "Saint Kitts and Nevis", dialCode: "+1869", alpha2: "KN", code: "kn" },
    { name: "Jamaica", dialCode: "+1876", alpha2: "JM", code: "jm" },
    { name: "Puerto Rico", dialCode: "+1939", alpha2: "PR", code: "pr" },
    { name: "Egypt", dialCode: "+20", alpha2: "EG", code: "eg" },
    { name: "South Sudan", dialCode: "+211", alpha2: "SS", code: "ss" },
    { name: "Morocco", dialCode: "+212", alpha2: "MA", code: "ma" },
    { name: "Algeria", dialCode: "+213", alpha2: "DZ", code: "dz" },
    { name: "Tunisia", dialCode: "+216", alpha2: "TN", code: "tn" },
    { name: "Libya", dialCode: "+218", alpha2: "LY", code: "ly" },
    { name: "Gambia", dialCode: "+220", alpha2: "GM", code: "gm" },
    { name: "Senegal", dialCode: "+221", alpha2: "SN", code: "sn" },
    { name: "Mauritania", dialCode: "+222", alpha2: "MR", code: "mr" },
    { name: "Mali", dialCode: "+223", alpha2: "ML", code: "ml" },
    { name: "Guinea", dialCode: "+224", alpha2: "GN", code: "gn" },
    { name: "Cote d'Ivoire", dialCode: "+225", alpha2: "CI", code: "ci" },
    { name: "Burkina Faso", dialCode: "+226", alpha2: "BF", code: "bf" },
    { name: "Niger", dialCode: "+227", alpha2: "NE", code: "ne" },
    { name: "Togo", dialCode: "+228", alpha2: "TG", code: "tg" },
    { name: "Benin", dialCode: "+229", alpha2: "BJ", code: "bj" },
    { name: "Mauritius", dialCode: "+230", alpha2: "MU", code: "mu" },
    { name: "Liberia", dialCode: "+231", alpha2: "LR", code: "lr" },
    { name: "Sierra Leone", dialCode: "+232", alpha2: "SL", code: "sl" },
    { name: "Ghana", dialCode: "+233", alpha2: "GH", code: "gh" },
    { name: "Nigeria", dialCode: "+234", alpha2: "NG", code: "ng" },
    { name: "Chad", dialCode: "+235", alpha2: "TD", code: "td" },
    { name: "Central African Republic", dialCode: "+236", alpha2: "CF", code: "cf" },
    { name: "Cameroon", dialCode: "+237", alpha2: "CM", code: "cm" },
    { name: "Cape Verde", dialCode: "+238", alpha2: "CV", code: "cv" },
    { name: "Sao Tome and Principe", dialCode: "+239", alpha2: "ST", code: "st" },
    { name: "Equatorial Guinea", dialCode: "+240", alpha2: "GQ", code: "gq" },
    { name: "Gabon", dialCode: "+241", alpha2: "GA", code: "ga" },
    { name: "Congo", dialCode: "+242", alpha2: "CG", code: "cg" },
    { name: "Democratic Republic of the Congo", dialCode: "+243", alpha2: "CD", code: "cd" },
    { name: "Angola", dialCode: "+244", alpha2: "AO", code: "ao" },
    { name: "Guinea-Bissau", dialCode: "+245", alpha2: "GW", code: "gw" },
    { name: "British Indian Ocean Territory", dialCode: "+246", alpha2: "IO", code: "io" },
    { name: "Seychelles", dialCode: "+248", alpha2: "SC", code: "sc" },
    { name: "Sudan", dialCode: "+249", alpha2: "SD", code: "sd" },
    { name: "Rwanda", dialCode: "+250", alpha2: "RW", code: "rw" },
    { name: "Ethiopia", dialCode: "+251", alpha2: "ET", code: "et" },
    { name: "Somalia", dialCode: "+252", alpha2: "SO", code: "so" },
    { name: "Djibouti", dialCode: "+253", alpha2: "DJ", code: "dj" },
    { name: "Kenya", dialCode: "+254", alpha2: "KE", code: "ke" },
    { name: "Tanzania", dialCode: "+255", alpha2: "TZ", code: "tz" },
    { name: "Uganda", dialCode: "+256", alpha2: "UG", code: "ug" },
    { name: "Burundi", dialCode: "+257", alpha2: "BI", code: "bi" },
    { name: "Mozambique", dialCode: "+258", alpha2: "MZ", code: "mz" },
    { name: "Zambia", dialCode: "+260", alpha2: "ZM", code: "zm" },
    { name: "Madagascar", dialCode: "+261", alpha2: "MG", code: "mg" },
    { name: "Mayotte", dialCode: "+262", alpha2: "YT", code: "yt" },
    { name: "Reunion", dialCode: "+262", alpha2: "RE", code: "re" },
    { name: "Zimbabwe", dialCode: "+263", alpha2: "ZW", code: "zw" },
    { name: "Namibia", dialCode: "+264", alpha2: "NA", code: "na" },
    { name: "Malawi", dialCode: "+265", alpha2: "MW", code: "mw" },
    { name: "Lesotho", dialCode: "+266", alpha2: "LS", code: "ls" },
    { name: "Botswana", dialCode: "+267", alpha2: "BW", code: "bw" },
    { name: "Swaziland", dialCode: "+268", alpha2: "SZ", code: "sz" },
    { name: "Comoros", dialCode: "+269", alpha2: "KM", code: "km" },
    { name: "South Africa", dialCode: "+27", alpha2: "ZA", code: "za" },
    { name: "Saint Helena", dialCode: "+290", alpha2: "SH", code: "sh" },
    { name: "Eritrea", dialCode: "+291", alpha2: "ER", code: "er" },
    { name: "Aruba", dialCode: "+297", alpha2: "AW", code: "aw" },
    { name: "Faroe Islands", dialCode: "+298", alpha2: "FO", code: "fo" },
    { name: "Greenland", dialCode: "+299", alpha2: "GL", code: "gl" },
    { name: "Greece", dialCode: "+30", alpha2: "GR", code: "gr" },
    { name: "Netherlands", dialCode: "+31", alpha2: "NL", code: "nl" },
    { name: "Belgium", dialCode: "+32", alpha2: "BE", code: "be" },
    { name: "France", dialCode: "+33", alpha2: "FR", code: "fr" },
    { name: "Spain", dialCode: "+34", alpha2: "ES", code: "es" },
    { name: "Gibraltar", dialCode: "+350", alpha2: "GI", code: "gi" },
    { name: "Portugal", dialCode: "+351", alpha2: "PT", code: "pt" },
    { name: "Luxembourg", dialCode: "+352", alpha2: "LU", code: "lu" },
    { name: "Ireland", dialCode: "+353", alpha2: "IE", code: "ie" },
    { name: "Iceland", dialCode: "+354", alpha2: "IS", code: "is" },
    { name: "Albania", dialCode: "+355", alpha2: "AL", code: "al" },
    { name: "Malta", dialCode: "+356", alpha2: "MT", code: "mt" },
    { name: "Cyprus", dialCode: "+357", alpha2: "CY", code: "cy" },
    { name: "Finland", dialCode: "+358", alpha2: "FI", code: "fi" },
    { name: "Bulgaria", dialCode: "+359", alpha2: "BG", code: "bg" },
    { name: "Hungary", dialCode: "+36", alpha2: "HU", code: "hu" },
    { name: "Lithuania", dialCode: "+370", alpha2: "LT", code: "lt" },
    { name: "Latvia", dialCode: "+371", alpha2: "LV", code: "lv" },
    { name: "Estonia", dialCode: "+372", alpha2: "EE", code: "ee" },
    { name: "Moldova", dialCode: "+373", alpha2: "MD", code: "md" },
    { name: "Armenia", dialCode: "+374", alpha2: "AM", code: "am" },
    { name: "Belarus", dialCode: "+375", alpha2: "BY", code: "by" },
    { name: "Andorra", dialCode: "+376", alpha2: "AD", code: "ad" },
    { name: "Monaco", dialCode: "+377", alpha2: "MC", code: "mc" },
    { name: "San Marino", dialCode: "+378", alpha2: "SM", code: "sm" },
    { name: "Ukraine", dialCode: "+380", alpha2: "UA", code: "ua" },
    { name: "Serbia", dialCode: "+381", alpha2: "RS", code: "rs" },
    { name: "Montenegro", dialCode: "+382", alpha2: "ME", code: "me" },
    { name: "Kosovo", dialCode: "+383", alpha2: "XK", code: "xk" },
    { name: "Croatia", dialCode: "+385", alpha2: "HR", code: "hr" },
    { name: "Slovenia", dialCode: "+386", alpha2: "SI", code: "si" },
    { name: "Bosnia and Herzegovina", dialCode: "+387", alpha2: "BA", code: "ba" },
    { name: "North Macedonia", dialCode: "+389", alpha2: "MK", code: "mk" },
    { name: "Italy", dialCode: "+39", alpha2: "IT", code: "it" },
    { name: "Romania", dialCode: "+40", alpha2: "RO", code: "ro" },
    { name: "Switzerland", dialCode: "+41", alpha2: "CH", code: "ch" },
    { name: "Czech Republic", dialCode: "+420", alpha2: "CZ", code: "cz" },
    { name: "Slovakia", dialCode: "+421", alpha2: "SK", code: "sk" },
    { name: "Liechtenstein", dialCode: "+423", alpha2: "LI", code: "li" },
    { name: "Austria", dialCode: "+43", alpha2: "AT", code: "at" },
    { name: "United Kingdom", dialCode: "+44", alpha2: "GB", code: "gb" },
    { name: "Denmark", dialCode: "+45", alpha2: "DK", code: "dk" },
    { name: "Sweden", dialCode: "+46", alpha2: "SE", code: "se" },
    { name: "Norway", dialCode: "+47", alpha2: "NO", code: "no" },
    { name: "Poland", dialCode: "+48", alpha2: "PL", code: "pl" },
    { name: "Germany", dialCode: "+49", alpha2: "DE", code: "de" },
    { name: "Falkland Islands", dialCode: "+500", alpha2: "FK", code: "fk" },
    { name: "Belize", dialCode: "+501", alpha2: "BZ", code: "bz" },
    { name: "Guatemala", dialCode: "+502", alpha2: "GT", code: "gt" },
    { name: "El Salvador", dialCode: "+503", alpha2: "SV", code: "sv" },
    { name: "Honduras", dialCode: "+504", alpha2: "HN", code: "hn" },
    { name: "Nicaragua", dialCode: "+505", alpha2: "NI", code: "ni" },
    { name: "Costa Rica", dialCode: "+506", alpha2: "CR", code: "cr" },
    { name: "Panama", dialCode: "+507", alpha2: "PA", code: "pa" },
    { name: "Saint Pierre and Miquelon", dialCode: "+508", alpha2: "PM", code: "pm" },
    { name: "Haiti", dialCode: "+509", alpha2: "HT", code: "ht" },
    { name: "Peru", dialCode: "+51", alpha2: "PE", code: "pe" },
    { name: "Mexico", dialCode: "+52", alpha2: "MX", code: "mx" },
    { name: "Cuba", dialCode: "+53", alpha2: "CU", code: "cu" },
    { name: "Argentina", dialCode: "+54", alpha2: "AR", code: "ar" },
    { name: "Brazil", dialCode: "+55", alpha2: "BR", code: "br" },
    { name: "Chile", dialCode: "+56", alpha2: "CL", code: "cl" },
    { name: "Colombia", dialCode: "+57", alpha2: "CO", code: "co" },
    { name: "Venezuela", dialCode: "+58", alpha2: "VE", code: "ve" },
    { name: "Guadeloupe", dialCode: "+590", alpha2: "GP", code: "gp" },
    { name: "Bolivia", dialCode: "+591", alpha2: "BO", code: "bo" },
    { name: "Guyana", dialCode: "+592", alpha2: "GY", code: "gy" },
    { name: "Ecuador", dialCode: "+593", alpha2: "EC", code: "ec" },
    { name: "French Guiana", dialCode: "+594", alpha2: "GF", code: "gf" },
    { name: "Paraguay", dialCode: "+595", alpha2: "PY", code: "py" },
    { name: "Martinique", dialCode: "+596", alpha2: "MQ", code: "mq" },
    { name: "Suriname", dialCode: "+597", alpha2: "SR", code: "sr" },
    { name: "Uruguay", dialCode: "+598", alpha2: "UY", code: "uy" },
    { name: "Bonaire, Sint Eustatius and Saba", dialCode: "+599", alpha2: "BQ", code: "bq" },
    { name: "Malaysia", dialCode: "+60", alpha2: "MY", code: "my" },
    { name: "Australia", dialCode: "+61", alpha2: "AU", code: "au" },
    { name: "Indonesia", dialCode: "+62", alpha2: "ID", code: "id" },
    { name: "Philippines", dialCode: "+63", alpha2: "PH", code: "ph" },
    { name: "New Zealand", dialCode: "+64", alpha2: "NZ", code: "nz" },
    { name: "Singapore", dialCode: "+65", alpha2: "SG", code: "sg" },
    { name: "Thailand", dialCode: "+66", alpha2: "TH", code: "th" },
    { name: "Timor-Leste", dialCode: "+670", alpha2: "TL", code: "tl" },
    { name: "Norfolk Island", dialCode: "+672", alpha2: "NF", code: "nf" },
    { name: "Brunei Darussalam", dialCode: "+673", alpha2: "BN", code: "bn" },
    { name: "Nauru", dialCode: "+674", alpha2: "NR", code: "nr" },
    { name: "Papua New Guinea", dialCode: "+675", alpha2: "PG", code: "pg" },
    { name: "Tonga", dialCode: "+676", alpha2: "TO", code: "to" },
    { name: "Solomon Islands", dialCode: "+677", alpha2: "SB", code: "sb" },
    { name: "Vanuatu", dialCode: "+678", alpha2: "VU", code: "vu" },
    { name: "Fiji", dialCode: "+679", alpha2: "FJ", code: "fj" },
    { name: "Palau", dialCode: "+680", alpha2: "PW", code: "pw" },
    { name: "Wallis and Futuna", dialCode: "+681", alpha2: "WF", code: "wf" },
    { name: "Cook Islands", dialCode: "+682", alpha2: "CK", code: "ck" },
    { name: "Niue", dialCode: "+683", alpha2: "NU", code: "nu" },
    { name: "Samoa", dialCode: "+685", alpha2: "WS", code: "ws" },
    { name: "Kiribati", dialCode: "+686", alpha2: "KI", code: "ki" },
    { name: "New Caledonia", dialCode: "+687", alpha2: "NC", code: "nc" },
    { name: "Tuvalu", dialCode: "+688", alpha2: "TV", code: "tv" },
    { name: "French Polynesia", dialCode: "+689", alpha2: "PF", code: "pf" },
    { name: "Tokelau", dialCode: "+690", alpha2: "TK", code: "tk" },
    { name: "Micronesia, Federated States of Micronesia", dialCode: "+691", alpha2: "FM", code: "fm" },
    { name: "Marshall Islands", dialCode: "+692", alpha2: "MH", code: "mh" }
]

export default Countries;